global:
  scrape_interval: 25s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: ubuntu
  static_configs:  
  - targets:
    - 192.168.33.10:9100
